#!/usr/bin/perl
# KPG/Kw's Page Generator
# Part of KRU
# Copyright Kwpolska 2010. Licensed on GPLv3.
# Portions copyright Enlik 2010.
#USAGE: ./kpg /location/of/the/markdowned/file
use warnings;
use strict;
# QUOTE-UNQUOTE CONFIG
my $template = "./kpgtemplate.html"; # where is the template file?
my $pathtomarkdown = "./Markdown.pl"; #where is the markdown file?
# END OF CONFIG
#grabbing variables...
my $base = $ARGV[0];
my $location = $base.".html";
#opening files...
open my $from, '<', $template or die "Can't read the template! $!\n";
open my $to, '>', $location or die "Can't create the destination file! $!\n";
open my $basefh, '+<', $base or die "Can't read the title from base file! $!\n";
#reading title...
my @bfile = <$basefh>;
my $title = $bfile['0'];
#parsing...
open my $fh, '-|', $pathtomarkdown, $base or die "Can't parse the content! Is the path correct? $!\n"; my $contents = do { local $/; <$fh> };
#I guess we're there.
while(<$from>) {
	$_ =~ s/_KPGTITLE_/$title/;
	$_ =~ s/_KPGCONTENTS_/$contents/;
	print $to $_;
}
#we're done!
print "$location\n";
