#!/usr/bin/perl
# KPG/Kw's Page Generator
# Part of KRU
# Copyright Kwpolska 2010. Licensed on GPLv3.
# Portions copyright Enlik 2010.
#USAGE: ./kpg file1 [file2] [file3] (and more)
use warnings;
use strict;
use File::Basename;
# QUOTE-UNQUOTE CONFIG
my $template = "/home/Kwpolska/kpgtemplate.html"; # where is the template file?
my $pathtomarkdown = "/home/Kwpolska/bin/Markdown.pl"; #where is the markdown file?
# END OF CONFIG
sub generate {
my $base=shift;
my $basename = fileparse($base, qr/\.[^.]*/);
my $location = $basename.".html";
#opening files
open my $from, '<', $template or die "Can't read the template! $!\n";
open my $to, '>', $location or die "Can't create the destination file! $!\n";
open my $basefh, '+<', $base or die "Can't read the title from base file! $!\n";
#this hack is made for reading the title
my @bfile = <$basefh>;
my $title = $bfile['0'];
#now we can parse it.
open my $fh, '-|', $pathtomarkdown, $base or die "Can't parse the content! Is the path correct? $!\n"; my $content = do { local $/; <$fh> };
#I guess that's it.
while(<$from>) {
	$_ =~ s/_KPGTITLE_/$title/;
	$_ =~ s/_KPGCONTENT_/$content/;
	print $to $_;
}
#we're done!
print "$location\n";
}
my $argc = $#ARGV + 1;
my $i = 0;
while ($i != $argc) {
	my $arg = $ARGV[$i]; #There was no other way.
	generate($arg);
	$i = $i + 1;
}
