#!/bin/bash
#unpack
#Licensed on PD. By Kwpolska.
for file in "$@"; 
do
if [ -f "$file" ] ; then
     case "$file" in
        *.tar.bz2) tar xjf $file ;;
        *.tar.gz) tar xzf $file ;;
        *.bz2) bunzip2 $file ;;
        *.rar) unrar x $file ;;
        *.gz) gunzip $file ;;
        *.tar) tar xf $file ;;
        *.tbz2) tar xjf $file ;;
        *.tgz) tar xzf $file ;;
        *.zip) unzip $file ;;
        *.Z) uncompress $file ;;
        *.7z) 7z x $file ;;
        *) echo "'$file' freaks out. cab? it sucks, man."
      esac
else
      echo "'$file'? Is it a file or a poem written in the argument(s)?"
fi
done
