#!/bin/bash
#unpack
#Licensed on PD. By Kwpolska.
echo "unpack v 0.1\nLicensed on PD. By Kwpolska."
if [ "$@" = "" ]; then
echo "Supported archives: tar.gz/tgz tbz2/tar.bz2 tar.lzma tar.xz lzma xz bz2 rar gz tar zip Z 7z cab"
fi
for file in "$@"; do
if [ -f "$file" ]; then
case "$file" in
*.tar.gz  | *.tgz) tar -xzvf $file ;;
*.tar.bz2 | *.tbz2) tar -xjvf $file ;;
*.tar.lzma) tar --lzma -xvf $file ;;
*.tar.xz) tar -xJvf $file ;;
*.lzma) lzma -dvv $file ;;
*.xz) xz -dvv $file ;;
*.bz2) bunzip2 $file ;;
*.rar) unrar x $file ;;
*.gz) gunzip $file ;;
*.tar) tar -xvf $file ;;
*.zip) unzip $file ;;
*.Z) uncompress $file ;;
*.7z) 7z x $file ;;
*.cab) cabextract $file ;;
*) echo "'$file' isn't a supported archive. Supported archives: tar.gz/tgz tar.bz2/tbz2 tar.lzma tar.xz lzma xz bz2 rar gz tar zip Z 7z cab"
esac
else
echo "'$file' is not a file. Supported archives: tar.gz/tgz tar.bz2/tbz2 tar.lzma tar.xz lzma xz bz2 rar gz tar zip Z 7z cab"
fi
done
