#!/bin/bash
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/games'
echo 'Git Commiter'
echo 'Copyright Kwpolska 2010. Licensed on GPLv3.'
echo 'Executed: '`date`
cd ~/git
for dirname in *
do
	echo "Entering directory $dirname"
	cd ~/git/$dirname
	git add ./*
	git commit -m "auto commit"
	git push
	cd ../
done
echo "Done."
