#!/bin/zsh
#syu
#Copyright Kwpolska 2011.  Licensed under GPLv3.

#f(01) syuhelp
function syuhelp {
    echo "syu"
    echo "Copyright Kwpolska 2011.  Licensed under GPLv3."
    echo "Syntax: syu [arguments]"
    echo "  no arguments  Perform an update (pacman -Syu + packer -Syu)."
    echo "  -h --help     Show this message."
    echo "  -t --time     Update time."
    echo "  -l --lock     Unlock pacman database."
    echo "  -o --optimize Optimizes the database."
    echo "  -r --reflect  Run reflector."
    echo "  -c --cron     Perform a cron-friendly update (NTP + pacman -Sy)."
    echo "  -a --noaur    Disable packer from the update process."
    exit
}

#f(02) syutime
    function syutime {
    ntpdate pl.pool.ntp.org
}

#f(03) syunlock
function syunlock {
    rm /var/lib/pacman/db.lck
    echo "Database unlocked."
}

#f(04) syureflect
    function syureflect {
    echo "Running reflector."
    echo -n "Finished elements:"
    reflector -c Any > /etc/pacman.d/mirrorlist
    echo -n " Any"
    reflector -p http -c Germany >> /etc/pacman.d/mirrolist
    echo -n " Germany"
    reflector -p http -c United\ States >> /etc/pacman.d/mirrorlist
    echo -n " US"
    reflector -l 5 -p http >> /etc/pacman.d/mirrorlist
    echo -n " latest"
    reflector -f 5 -p http >> /etc/pacman.d/mirrorlist
    echo -n " fastest"
    #time reflector -f 10 -ro /etc/pacman.d/mirrorlist
    echo "Reflecting finished. Updating..."
    pacman -Syyu
    packer -Syyu
    exit
}

#f(05) syuoptimize
function syuoptimize {
    pacman-optimize
}

#f(06) syucron
function syucron {
    ntpdate pl.pool.ntp.org > /dev/null
    pacman -Sy > /dev/null
    exit
}

while true; do
    case "$1" in
        "-h" | "--help")     syuhelp    ; EXIT=s ;; #f(01)
        "-t" | "--time")     syutime    ; EXIT=y ;; #f(02)
        "-l" | "--lock")     syunlock   ; EXIT=y ;; #f(03)
        "-o" | "--optimize") syuoptimize; EXIT=y ;; #f(04)
        "-r" | "--reflect")  syureflect ; EXIT=n ;; #f(05)
        "-c" | "--cron")     syucron    ; EXIT=s ;; #f(06)
        "-a" | "--noaur")    syuaur="n" ; EXIT=n ;; #f(na)
    esac
    shift
done
if [ "$EXIT" = 'y' ]; then exit; fi
if [ "$EXIT" = 's' ]; then
    echo "WARNING:  the self-exit did not happen.  This is a bug."
    echo "File an issue at <https://github.com/Kwpolska/kru>."; exit 1
fi

pacman -Syu
if [ "$syuaur" != "n" ]; then
    packer -Syu
fi
