#!/bin/bash
echo 'Git Commiter'
echo 'Copyright Kwpolska 2010. Licensed on GPLv3.'
echo 'Executed: '`date`
cd ~/git
for dirname in *
do
    echo "Entering directory $dirname"
    cd ~/git/$dirname
    git commit -a $@
    git push
    cd ../
done
echo "Done."

