#!/bin/bash
echo 'Git Puller'
echo 'Copyright Kwpolska 2011. Licensed on GPLv3.'
echo 'Executed: '`date`
cd ~/git
for dirname in *
do
	echo "Entering directory $dirname"
	cd ~/git/$dirname
	git pull
	cd ../
done
echo "Done."
