#!/usr/bin/perl
# KwDocumentor
# Part of KRU
# Copyright Kwpolska 2010. Licensed on GPLv3.
# Portions copyright Enlik 2010.
use warnings;
use strict;
use Term::ANSIColor qw(:constants);
sub pb {
my $value=shift;
print BOLD, CYAN, '['.$value.'] ', RESET;
}
sub py {
my $value=shift;
print BOLD, YELLOW, '['.$value.'] ', RESET;
}
sub pg {
my $value=shift;
print BOLD, GREEN '['.$value.'] ', RESET;
}
pg("*");
print "KwDocumentator\n";
pg("*");
print "Copyright Kwpolska 2010. Licensed on GPLv3.\n";
#template:
#pb("id");
#print "what\n"
#py(">");
#my $value = <STDIN>;
pb("1");
print "Main program information\n";
py(">");
my $maininfo = <STDIN>;
pb("2");
print "Purpose\n";
py(">");
my $purpose = <STDIN>;
pb("3");
print "Install instructions\n";
py(">");
my $instructions = <STDIN>;
pb("4");
print "Additional notes - leave empty if needed\n";
py(">");
my $notesbase = <STDIN>;
pb("5");
print "Save the file as:\n";
py(">");
my $location = <STDIN>;
pg("*");
print "Preparing... ";
chomp($maininfo);
chomp($purpose);
chomp($instructions);
chomp($location);
chomp($notesbase);
my $notes = '';
#comment the 3 lines below if you don't want to use notes
if ($notesbase ne "") {
$notes = "\nNOTES:\n--------------\n$notesbase\n";
}
#end of commenting area
print "done\n";
pg("*");
print "Opening files... ";
open(my $th, '<', './kwdtemplate') or die "Can't read the template!";
open(my $fh, '>', $location) or die "Wrong chmods to $!";
print "done\n";
pg("*");
print "Filling and saving... ";
while(<$th>) {
	$_ =~ s/T_PURPOSE/$purpose/;
	$_ =~ s/T_MAININFO/$maininfo/;
	$_ =~ s/T_INSTRUCTIONS/$instructions/;
	$_ =~ s/T_NOTES/$notes/;
	#do you get the template? put below me lines like $_ =~ s/T_STRING_IN_THE_FILE/$variable_there/;
	print $fh $_; # lub print $fh_dest $_;
}
print "done\n";

