#!/bin/bash
#pkgman
#PKGBUILDer-pacman wrapper
#Part of KRU
#Copyright Kwpolska 2011.  Licensed under GPLv3.
case "$1" in
    '-h'   | '--help')          echo "pkgman, PKGBUILDERer-pacman wrapper.  Standard pacman syntax applies." ;;
    '-S'   | '--sync')          if pacman "$@" -i &> /dev/null; then pacman "$@"; else pkgbuilder "$@" ; fi ;;
    '-Si'  | '--sync --info')   if pacman "$@" -i &> /dev/null; then pacman "$@"; else pkgbuilder "$@"; fi ;;
    '-Ss'  | '--sync --search') pacman "$@"; pkgbuilder "$@" ;;
    '-Syu' | '-Su' | '-Syyu')   pacman "$@"; pkgbuilder "$@" ;; # --sync --refresh --sysupgrade is too long.
    *)                          pacman "$@"                     # -R and other actions that can't be done by PKGBUILDer are given to pacman.
esac
