#!/bin/bash
# An implementation of the Euclidean Algorithm in bash.
# Copyright 2012 Kwpolska.  See ./LICENSE for licensing details.

a=$1
b=$2
while [ "$b" != "0" ]; do;
    c=$[$a % $b]
    a=$b
    b=$c
done
echo $a
