#!/bin/bash
#Kw's Maintenance script

#(0) If requested, unlock the pacman DBs.
if [ "$1" = "--lock" ]; then
rm /var/lib/pacman/db.lck
exit
fi

#(1) Update time.
#1.1 Hacks for updating time quietly (cron)
if [ "$1" = "--time" ]; then
ntpdate pl.pool.ntp.org 2> /dev/null
exit
fi
if [ "$1" = "--cron" ]; then
ntpdate pl.pool.ntp.org > /dev/null
clyde -Sy > /dev/null
pacman -Sy > /dev/null
exit
fi

#non-quiet option
ntpdate pl.pool.ntp.org

#1.9 If requested, run reflector.
if [ "$1" = "--reflect" ]; then
echo "Running reflector. This might take up to 10 minutes (or even longer)."
time reflector -f 10 -ro /etc/pacman.d/mirrorlist
echo "Please run the script once again without --reflect to update."
fi

#(2) Update the system itself.
pacman -Syyu
#2.1 If we don't have --noaur, perform clyde's AUR update.
if [ "$1" != "--noaur" ]; then
clyde -Syyu --aur
fi

